server:
  port: 8082

spring:
  application:
    name: mail-service
  profiles.active: local
  rabbitmq:
    password: guest
    port: 15672
    username: guest
    exchange: email.exchange
    queue: email.queue
    routingkey: email.routingkey

---
spring:
  profiles: local
  rabbitmq:
    host: localhost

---
spring:
  profiles: docker
  rabbitmq:
    host: rabbitmq
