version: '3'

services:
  postgres:
    container_name: subscription_db
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_USER: subscriptions
      POSTGRES_PASSWORD: subscriptions
      POSTGRES_DB: subscriptions
    volumes:
       - ~/storage/subscriptions/postgres:/data/postgres
    ports:
      - "5433:5432"