version: '3'

services:
  postgres:
    container_name: subscription_db
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_USER: subscriptions
      POSTGRES_PASSWORD: subscriptions
      POSTGRES_DB: subscriptions
    volumes:
       - ~/storage/subscriptions/postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - mail_subscription

  rabbitmq:
    container_name: subscription_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
     - ~/storage/subscriptions/rabbitmq:/var/lib/rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    networks:
      - mail_subscription

  public-service:
    build:
      context: ./publicService/
      dockerfile: Dockerfile
    image: public-service
    container_name: public-service
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
    ports:
      - "8080:8080" 
    networks:
      - mail_subscription
    
  subscription-service:
    build:
      context: ./subscriptionService/
      dockerfile: Dockerfile
    image: subscription-service
    container_name: subscription-service
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
    ports:
      - "8081:8081"
    depends_on: 
      - postgres
      - rabbitmq
    networks:
      - mail_subscription
    
  mail-service:
    build:
      context: ./mailService/
      dockerfile: Dockerfile
    image: mail-service
    container_name: mail-service
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
    ports:
      - "8082:8082"
    links:
      - "rabbitmq"
    depends_on:
      - "rabbitmq"
    networks:
      - mail_subscription

networks:
  mail_subscription:
    driver: bridge