version: '3'

services:
  postgres:
    container_name: subscription_db
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_USER: subscriptions
      POSTGRES_PASSWORD: subscriptions
      POSTGRES_DB: subscriptions
    volumes:
       - ~/storage/subscriptions/postgres:/data/postgres
    ports:
      - "5433:5432"

  rabbitmq:
    container_name: subscription_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
     - ~/storage/subscriptions/rabbitmq:/var/lib/rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"