server:
  port: 8080

spring:
  application:
    name: public-service
  profiles.active: local

---
spring:
  profiles: local

feign:
  client:
    url: https://localhost:8081
---
spring:
  profiles: docker

feign:
  client:
    url: https://subscription-service:8081
